apiVersion: v1
name: event-exporter
version: 0.1.0
description: "event-exporter"
icon: "https://docs.helm.sh/src/img/helm-logo.svg"
keywords:
  - kubernetes
home: https://github.com/gerald1248/event-exporter
sources:
  - https://github.com/gerald1248/event-exporter
maintainers:
  - name: gerald1248
    email: gerald1248@gmail.com
