apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding 
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace | quote }}
